template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "ston1242"
__REPO__ = "lang-sto"
__UND2C__ = "sto"
__UNDEFINED__ = "Stoney"
__UND__ = "sto"
