template = "https://github.com/giellalt/template-lang-und"
rev_id = 320
template_sha = "67266bcec9c778bce3d70cc0a78e75bdec65cc66"

[replacements]
__GLOTTOLOG_ID__ = "ston1242"
__REPO__ = "lang-sto"
__UND2C__ = "sto"
__UNDEFINED__ = "Stoney"
__UND__ = "sto"
