[package]
name = "sto"
human_name = "Stoney"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.sto]
filename = "sto-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-sto"
platform = "windows"
uuid = "93496C2D-DE2A-4655-8833-2CE4B5B83335"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.sto"
package = "speller-sto"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-sto-mso"
platform = "windows"
uuid = "4A727A95-491A-48A8-A83F-8ACFE815E24B"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-sto"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
